version: "3.8"

services:
  email-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apex-email-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/v1/send-email",
        ]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 40s
    networks:
      - email-network

networks:
  email-network:
    driver: bridge
